In [4]:
!pip install pandas

Collecting pandas
  Downloading pandas-2.3.3-cp310-cp310-win_amd64.whl (11.3 MB)
     ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
     - -------------------------------------- 0.5/11.3 MB 9.4 MB/s eta 0:00:02
     -- ------------------------------------- 0.7/11.3 MB 7.3 MB/s eta 0:00:02
     --- ------------------------------------ 0.9/11.3 MB 6.2 MB/s eta 0:00:02
     --- ------------------------------------ 1.1/11.3 MB 5.7 MB/s eta 0:00:02
     ---- ----------------------------------- 1.3/11.3 MB 5.4 MB/s eta 0:00:02
     ----- ---------------------------------- 1.5/11.3 MB 5.1 MB/s eta 0:00:02
     ----- ---------------------------------- 1.6/11.3 MB 4.8 MB/s eta 0:00:03
     ------ --------------------------------- 1.8/11.3 MB 4.7 MB/s eta 0:00:03
     ------- -------------------------------- 2.0/11.3 MB 4.6 MB/s eta 0:00:03
     ------- -------------------------------- 2.2/11.3 MB 4.6 MB/s eta 0:00:02
     -------- ------------------------------- 2.4/11.3 MB 4.6 MB/s eta 0:00:02
     -------- ------------------------------- 2.5/11.3 MB 4.5 MB/s eta 0:00:02
     --------- ------------------------------ 2.7/11.3 MB 4.4 MB/s eta 0:00:02
     --------- ------------------------------ 2.7/11.3 MB 4.4 MB/s eta 0:00:02
     --------- ------------------------------ 2.7/11.3 MB 4.4 MB/s eta 0:00:02
     ----------- ---------------------------- 3.3/11.3 MB 4.3 MB/s eta 0:00:02
     ------------ --------------------------- 3.4/11.3 MB 4.3 MB/s eta 0:00:02
     ------------ --------------------------- 3.6/11.3 MB 4.3 MB/s eta 0:00:02
     ------------- -------------------------- 3.8/11.3 MB 4.3 MB/s eta 0:00:02
     ------------- -------------------------- 4.0/11.3 MB 4.2 MB/s eta 0:00:02
     -------------- ------------------------- 4.1/11.3 MB 4.2 MB/s eta 0:00:02
     --------------- ------------------------ 4.3/11.3 MB 4.2 MB/s eta 0:00:02
     --------------- ------------------------ 4.5/11.3 MB 4.2 MB/s eta 0:00:02
     ---------------- ----------------------- 4.7/11.3 MB 4.2 MB/s eta 0:00:02
     ----------------- ---------------------- 4.9/11.3 MB 4.2 MB/s eta 0:00:02
     ----------------- ---------------------- 5.1/11.3 MB 4.1 MB/s eta 0:00:02
     ------------------ --------------------- 5.3/11.3 MB 4.1 MB/s eta 0:00:02
     ------------------- -------------------- 5.4/11.3 MB 4.1 MB/s eta 0:00:02
     ------------------- -------------------- 5.6/11.3 MB 4.1 MB/s eta 0:00:02
     -------------------- ------------------- 5.8/11.3 MB 4.1 MB/s eta 0:00:02
     --------------------- ------------------ 6.0/11.3 MB 4.1 MB/s eta 0:00:02
     --------------------- ------------------ 6.1/11.3 MB 4.1 MB/s eta 0:00:02
     ---------------------- ----------------- 6.3/11.3 MB 4.1 MB/s eta 0:00:02
     ---------------------- ----------------- 6.5/11.3 MB 4.1 MB/s eta 0:00:02
     ----------------------- ---------------- 6.7/11.3 MB 4.1 MB/s eta 0:00:02
     ------------------------ --------------- 6.9/11.3 MB 4.1 MB/s eta 0:00:02
     ------------------------ --------------- 7.0/11.3 MB 4.1 MB/s eta 0:00:02
     ------------------------- -------------- 7.2/11.3 MB 4.1 MB/s eta 0:00:02
     ------------------------- -------------- 7.3/11.3 MB 4.1 MB/s eta 0:00:01
     -------------------------- ------------- 7.5/11.3 MB 4.0 MB/s eta 0:00:01
     --------------------------- ------------ 7.7/11.3 MB 4.1 MB/s eta 0:00:01
     --------------------------- ------------ 7.9/11.3 MB 4.1 MB/s eta 0:00:01
     ---------------------------- ----------- 8.1/11.3 MB 4.0 MB/s eta 0:00:01
     ----------------------------- ---------- 8.2/11.3 MB 4.0 MB/s eta 0:00:01
     ----------------------------- ---------- 8.4/11.3 MB 4.0 MB/s eta 0:00:01
     ------------------------------ --------- 8.6/11.3 MB 4.0 MB/s eta 0:00:01
     ------------------------------- -------- 8.8/11.3 MB 4.0 MB/s eta 0:00:01
     ------------------------------- -------- 9.0/11.3 MB 4.0 MB/s eta 0:00:01
     -------------------------------- ------- 9.2/11.3 MB 4.0 MB/s eta 0:00:01
     -------------------------------- ------- 9.3/11.3 MB 4.0 MB/s eta 0:00:01
     --------------------------------- ------ 9.5/11.3 MB 4.0 MB/s eta 0:00:01
     ---------------------------------- ----- 9.7/11.3 MB 4.0 MB/s eta 0:00:01
     ---------------------------------- ----- 9.8/11.3 MB 4.0 MB/s eta 0:00:01
     ----------------------------------- ---- 10.0/11.3 MB 4.0 MB/s eta 0:00:01
     ----------------------------------- ---- 10.2/11.3 MB 4.0 MB/s eta 0:00:01
     ------------------------------------ --- 10.4/11.3 MB 4.0 MB/s eta 0:00:01
     ------------------------------------- -- 10.5/11.3 MB 4.0 MB/s eta 0:00:01
     ------------------------------------- -- 10.7/11.3 MB 3.9 MB/s eta 0:00:01
     -------------------------------------- - 10.9/11.3 MB 3.9 MB/s eta 0:00:01
     -------------------------------------- - 11.0/11.3 MB 3.9 MB/s eta 0:00:01
     ---------------------------------------  11.2/11.3 MB 3.9 MB/s eta 0:00:01
     ---------------------------------------  11.3/11.3 MB 3.9 MB/s eta 0:00:01
     ---------------------------------------- 11.3/11.3 MB 3.8 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dheepes\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.9.0.post0)
Collecting numpy>=1.22.4
  Downloading numpy-2.2.6-cp310-cp310-win_amd64.whl (12.9 MB)
     ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
     - -------------------------------------- 0.5/12.9 MB 16.8 MB/s eta 0:00:01
     -- ------------------------------------- 0.7/12.9 MB 8.8 MB/s eta 0:00:02
     -- ------------------------------------- 0.9/12.9 MB 7.0 MB/s eta 0:00:02
     --- ------------------------------------ 1.1/12.9 MB 6.2 MB/s eta 0:00:02
     --- ------------------------------------ 1.3/12.9 MB 5.8 MB/s eta 0:00:03
     ---- ----------------------------------- 1.4/12.9 MB 5.3 MB/s eta 0:00:03
     ----- ---------------------------------- 1.6/12.9 MB 5.2 MB/s eta 0:00:03
     ----- ---------------------------------- 1.8/12.9 MB 5.0 MB/s eta 0:00:03
     ------ --------------------------------- 2.0/12.9 MB 4.9 MB/s eta 0:00:03
     ------ --------------------------------- 2.2/12.9 MB 4.8 MB/s eta 0:00:03
     ------- -------------------------------- 2.3/12.9 MB 4.6 MB/s eta 0:00:03
     ------- -------------------------------- 2.5/12.9 MB 4.6 MB/s eta 0:00:03
     -------- ------------------------------- 2.7/12.9 MB 4.5 MB/s eta 0:00:03
     -------- ------------------------------- 2.8/12.9 MB 4.5 MB/s eta 0:00:03
     --------- ------------------------------ 3.0/12.9 MB 4.5 MB/s eta 0:00:03
     --------- ------------------------------ 3.2/12.9 MB 4.4 MB/s eta 0:00:03
     --------- ------------------------------ 3.2/12.9 MB 4.4 MB/s eta 0:00:03
     --------- ------------------------------ 3.2/12.9 MB 4.4 MB/s eta 0:00:03
     ----------- ---------------------------- 3.7/12.9 MB 4.4 MB/s eta 0:00:03
     ------------ --------------------------- 3.9/12.9 MB 4.3 MB/s eta 0:00:03
     ------------ --------------------------- 4.1/12.9 MB 4.2 MB/s eta 0:00:03
     ------------- -------------------------- 4.3/12.9 MB 4.2 MB/s eta 0:00:03
     ------------- -------------------------- 4.4/12.9 MB 4.1 MB/s eta 0:00:03
     -------------- ------------------------- 4.6/12.9 MB 4.1 MB/s eta 0:00:03
     -------------- ------------------------- 4.7/12.9 MB 4.1 MB/s eta 0:00:02
     --------------- ------------------------ 4.9/12.9 MB 4.1 MB/s eta 0:00:02
     --------------- ------------------------ 5.0/12.9 MB 4.0 MB/s eta 0:00:02
     ---------------- ----------------------- 5.2/12.9 MB 4.0 MB/s eta 0:00:02
     ---------------- ----------------------- 5.3/12.9 MB 4.0 MB/s eta 0:00:02
     ----------------- ---------------------- 5.5/12.9 MB 4.0 MB/s eta 0:00:02
     ----------------- ---------------------- 5.6/12.9 MB 3.9 MB/s eta 0:00:02
     ----------------- ---------------------- 5.8/12.9 MB 3.9 MB/s eta 0:00:02
     ------------------ --------------------- 5.9/12.9 MB 3.9 MB/s eta 0:00:02
     ------------------ --------------------- 6.1/12.9 MB 3.9 MB/s eta 0:00:02
     ------------------- -------------------- 6.3/12.9 MB 3.9 MB/s eta 0:00:02
     ------------------- -------------------- 6.4/12.9 MB 3.9 MB/s eta 0:00:02
     -------------------- ------------------- 6.6/12.9 MB 3.8 MB/s eta 0:00:02
     -------------------- ------------------- 6.7/12.9 MB 3.9 MB/s eta 0:00:02
     --------------------- ------------------ 6.8/12.9 MB 3.8 MB/s eta 0:00:02
     --------------------- ------------------ 7.0/12.9 MB 3.8 MB/s eta 0:00:02
     ---------------------- ----------------- 7.2/12.9 MB 3.8 MB/s eta 0:00:02
     ---------------------- ----------------- 7.4/12.9 MB 3.8 MB/s eta 0:00:02
     ----------------------- ---------------- 7.5/12.9 MB 3.8 MB/s eta 0:00:02
     ----------------------- ---------------- 7.7/12.9 MB 3.8 MB/s eta 0:00:02
     ------------------------ --------------- 7.9/12.9 MB 3.8 MB/s eta 0:00:02
     ------------------------ --------------- 8.0/12.9 MB 3.8 MB/s eta 0:00:02
     ------------------------- -------------- 8.2/12.9 MB 3.8 MB/s eta 0:00:02
     ------------------------- -------------- 8.4/12.9 MB 3.8 MB/s eta 0:00:02
     -------------------------- ------------- 8.5/12.9 MB 3.8 MB/s eta 0:00:02
     -------------------------- ------------- 8.7/12.9 MB 3.8 MB/s eta 0:00:02
     --------------------------- ------------ 8.9/12.9 MB 3.8 MB/s eta 0:00:02
     ---------------------------- ----------- 9.0/12.9 MB 3.8 MB/s eta 0:00:02
     ---------------------------- ----------- 9.2/12.9 MB 3.8 MB/s eta 0:00:01
     ---------------------------- ----------- 9.3/12.9 MB 3.8 MB/s eta 0:00:01
     ----------------------------- ---------- 9.5/12.9 MB 3.8 MB/s eta 0:00:01
     ----------------------------- ---------- 9.7/12.9 MB 3.8 MB/s eta 0:00:01
     ------------------------------ --------- 9.8/12.9 MB 3.8 MB/s eta 0:00:01
     ------------------------------- -------- 10.0/12.9 MB 3.8 MB/s eta 0:00:01
     ------------------------------- -------- 10.2/12.9 MB 3.8 MB/s eta 0:00:01
     -------------------------------- ------- 10.3/12.9 MB 3.8 MB/s eta 0:00:01
     -------------------------------- ------- 10.5/12.9 MB 3.7 MB/s eta 0:00:01
     --------------------------------- ------ 10.7/12.9 MB 3.7 MB/s eta 0:00:01
     --------------------------------- ------ 10.8/12.9 MB 3.7 MB/s eta 0:00:01
     ---------------------------------- ----- 11.0/12.9 MB 3.7 MB/s eta 0:00:01
     ---------------------------------- ----- 11.2/12.9 MB 3.7 MB/s eta 0:00:01
     ----------------------------------- ---- 11.3/12.9 MB 3.6 MB/s eta 0:00:01
     ----------------------------------- ---- 11.5/12.9 MB 3.6 MB/s eta 0:00:01
     ------------------------------------ --- 11.7/12.9 MB 3.7 MB/s eta 0:00:01
     ------------------------------------ --- 11.9/12.9 MB 3.6 MB/s eta 0:00:01
     ------------------------------------- -- 12.0/12.9 MB 3.7 MB/s eta 0:00:01
     ------------------------------------- -- 12.2/12.9 MB 3.6 MB/s eta 0:00:01
     -------------------------------------- - 12.3/12.9 MB 3.6 MB/s eta 0:00:01
     -------------------------------------- - 12.5/12.9 MB 3.7 MB/s eta 0:00:01
     ---------------------------------------  12.7/12.9 MB 3.6 MB/s eta 0:00:01
     ---------------------------------------  12.8/12.9 MB 3.6 MB/s eta 0:00:01
     ---------------------------------------  12.9/12.9 MB 3.7 MB/s eta 0:00:01
     ---------------------------------------- 12.9/12.9 MB 3.6 MB/s eta 0:00:00
Collecting pytz>=2020.1
  Downloading pytz-2026.1.post1-py2.py3-none-any.whl (510 kB)
     ---------------------------------------- 0.0/510.5 kB ? eta -:--:--
     ------------------------------------- 510.5/510.5 kB 15.6 MB/s eta 0:00:00
Requirement already satisfied: tzdata>=2022.7 in c:\users\dheepes\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\dheepes\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Installing collected packages: pytz, numpy, pandas
Successfully installed numpy-2.2.6 pandas-2.3.3 pytz-2026.1.post1

[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
import os
os.getcwd()

'C:\\Users\\Dheepes\\Desktop\\customer sales'

In [12]:
os.listdir()

['.ipynb_checkpoints', 'customer_shopping_behavior.csv', 'Untitled.ipynb']

In [16]:
df = pd.read_csv(r"C:\Users\Dheepes\Desktop\customer sales\customer_shopping_behavior.csv")

In [17]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [19]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [21]:
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x:x.fillna(x.median()))

In [23]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [29]:
df.columns= df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_') 
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [30]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [32]:
#create a new column 
labels=['Young Adult','Middle-aged','Senior','Adult']
df['age_group']=pd.qcut(df['age'],q=4,labels= labels)

In [33]:
df[['age','age_group']].head(10)

   age    age_group
0   55       Senior
1   19  Young Adult
2   50       Senior
3   21  Young Adult
4   45       Senior
5   46       Senior
6   63        Adult
7   27  Young Adult
8   26  Young Adult
9   57       Senior

In [35]:
#creating a purchase_freq_days col

frequency_mapping = {
    'fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annualy': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days']= df['frequency_of_purchases'].map(frequency_mapping)

In [36]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                      NaN            Fortnightly
1                      NaN            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                      NaN               Annually
5                      7.0                 Weekly
6                     90.0              Quarterly
7                      7.0                 Weekly
8                      NaN               Annually
9                     90.0              Quarterly

In [37]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [38]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [39]:
df=df.drop('promo_code_used',axis=1)

In [40]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [41]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binaryNote: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

  Downloading psycopg2_binary-2.9.12-cp310-cp310-win_amd64.whl (2.8 MB)
     ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
     -- ------------------------------------- 0.2/2.8 MB 9.6 MB/s eta 0:00:01
     ------ --------------------------------- 0.5/2.8 MB 7.0 MB/s eta 0:00:01
     ------- -------------------------------- 0.5/2.8 MB 4.7 MB/s eta 0:00:01
     --------- ------------------------------ 0.7/2.8 MB 4.3 MB/s eta 0:00:01
     -------------- ------------------------- 1.0/2.8 MB 4.8 MB/s eta 0:00:01
     -------------- ------------------------- 1.0/2.8 MB 4.6 MB/s eta 0:00:01
     -------------- ------------------------- 1.0/2.8 MB 4.6 MB/s eta 0:00:01
     -------------- ------------------------- 1.0/2.8 MB 4.6 MB/s eta 0:00:01
     ---------------- ----------------------- 1.1/2.8 MB 2.9 MB/s eta 0:00:01
     ------------------- -------------------- 1.3/2.8 MB 3.0 MB/s eta 0:00:01
     ------------------- -------------------- 1.3/2.8 MB 3.0 MB/s eta 0:00:01
     ------------------- -------------------- 1.3/2.8 MB 3.0 MB/s eta 0:00:01
     ------------------- -------------------- 1.3/2.8 MB 3.0 MB/s eta 0:00:01
     --------------------- ------------------ 1.5/2.8 MB 2.3 MB/s eta 0:00:01
     ----------------------- ---------------- 1.6/2.8 MB 2.5 MB/s eta 0:00:01
     ----------------------- ---------------- 1.6/2.8 MB 2.5 MB/s eta 0:00:01
     ----------------------- ---------------- 1.6/2.8 MB 2.5 MB/s eta 0:00:01
     -------------------------- ------------- 1.8/2.8 MB 2.0 MB/s eta 0:00:01
     --------------------------- ------------ 1.9/2.8 MB 1.9 MB/s eta 0:00:01
     ------------------------------ --------- 2.1/2.8 MB 1.9 MB/s eta 0:00:01
     ------------------------------- -------- 2.1/2.8 MB 1.9 MB/s eta 0:00:01
     ------------------------------------ --- 2.5/2.8 MB 2.2 MB/s eta 0:00:01
     ------------------------------------ --- 2.5/2.8 MB 2.2 MB/s eta 0:00:01
     ------------------------------------ --- 2.5/2.8 MB 2.2 MB/s eta 0:00:01
     ------------------------------------ --- 2.5/2.8 MB 2.2 MB/s eta 0:00:01
     ------------------------------------- -- 2.6/2.8 MB 1.9 MB/s eta 0:00:01
     ---------------------------------------  2.7/2.8 MB 2.0 MB/s eta 0:00:01
     ---------------------------------------  2.7/2.8 MB 2.0 MB/s eta 0:00:01
     ---------------------------------------  2.7/2.8 MB 2.0 MB/s eta 0:00:01
     ---------------------------------------  2.7/2.8 MB 2.0 MB/s eta 0:00:01
     ---------------------------------------  2.7/2.8 MB 2.0 MB/s eta 0:00:01
     ---------------------------------------  2.8/2.8 MB 1.7 MB/s eta 0:00:01
     ---------------------------------------- 2.8/2.8 MB 1.7 MB/s eta 0:00:00
Requirement already satisfied: sqlalchemy in c:\users\dheepes\appdata\local\programs\python\python310\lib\site-packages (2.0.48)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\dheepes\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: greenlet>=1 in c:\users\dheepes\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (3.3.2)
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12

In [8]:
!pip install psycopg2-binary --user

Requirement already satisfied: psycopg2-binary in c:\users\dheepes\appdata\local\programs\python\python310\lib\site-packages (2.9.12)

[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
import pandas as pd
from sqlalchemy import create_engine

# Load data
df = pd.read_csv(r"C:\Users\Dheepes\Desktop\customer sales\customer_shopping_behavior.csv")

# DB connection
username = "postgres"
password = "dheepika"
host = "localhost"
port = "5432"
database = "customer_behaviour"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

# Load into PostgreSQL
table_name = "customer"
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into '{table_name}' table.")

Data successfully loaded into 'customer' table.